### ISSUE TITLE
prodigal not ended correctly?

### ISSUE THREAD

**Issue by Sanrrone** [KennthShang/PhaMer#17]
My code
```
SDIR="/home/svalenzuela/software"
sname="HeP-24"
python $SDIR/PhaMer/preprocessing.py --dbdir $SDIR/PhaMer/database --contigs ${sname}_prophages.fasta --threads 16 --len 1000 --midfolder ${sname}_tmpphamer
python $SDIR/PhaMer/PhaMer.py --dbdir $SDIR/PhaMer/database --threads 16 --out ${sname}_phamer.csv --midfolder ${sname}_tmpphamer
```

and the output
```
Traceback (most recent call last):
  File "/scratch/project_2007362/software/PhaMer/preprocessing.py", line 70, in <module>
    _ = subprocess.check_call(prodigal_cmd, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/scratch/project_2007362/software/mambaforge/envs/phamer/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'pprodigal -T 16 -i HeP-24_tmpphamer/filtered_contigs.fa -a HeP-24_tmpphamer/test_protein.fa -f gff -p meta' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/scratch/project_2007362/software/PhaMer/PhaMer.py", line 41, in <module>
    pcs2idx = pkl.load(open(f'{transformer_fn}/pc2wordsid.dict', 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'HeP-24_tmpphamer/pc2wordsid.dict'
```
after editing `preprocessing.py` in order to track why is prodigal failing, but I couldn't get the error, seems like its ends correctly so I don't know where is the error.

what should I do?
thanks in advance!

**Comment by KennthShang** [comment]
Hi,

Please try to run

```
pprodigal -T 16 -i HeP-24_tmpphamer/filtered_contigs.fa -a HeP-24_tmpphamer/test_protein.fa -f gff -p meta
```

in your terminal to track the exact error.

Best,
Jiayu

**Comment by Sanrrone** [comment]
The command runs with no error with just giving a gff:
`pprodigal -T 16 -i HeP-24_tmpphamer/filtered_contigs.fa -a HeP-24_tmpphamer/test_protein.fa -f gff -p meta > result.txt`
```
(phamer) [valensan@puhti-login12 2_assembly]$ head result.txt 
##gff-version  3

# Sequence Data: seqnum=1;seqlen=20682;seqhdr="Scaffold_199:27422-48104"

# Model Data: version=Prodigal.v2.6.3;run_type=Metagenomic;model="17|Desulfotomaculum_acetoxidans_DSM_771|B|41.5|11|1";gc_cont=41.60;transl_table=11;uses_sd=1

Scaffold_199:27422-48104	Prodigal_v2.6.3	CDS	3	494	75.1	-	0	ID=1_1;partial=10;start_type=ATG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.455;conf=100.00;score=76.34;cscore=56.17;sscore=20.17;rscore=14.49;uscore=1.62;tscore=2.83;
Scaffold_199:27422-48104	Prodigal_v2.6.3	CDS	500	805	43.7	-	0	ID=1_2;partial=00;start_type=ATG;rbs_motif=AGGAG;rbs_spacer=5-10bp;gc_cont=0.425;conf=100.00;score=44.64;cscore=24.08;sscore=20.56;rscore=11.61;uscore=5.15;tscore=2.83;
Scaffold_199:27422-48104	Prodigal_v2.6.3	CDS	833	2041	127.1	-	0	ID=1_3;partial=00;start_type=ATG;rbs_motif=GGAGG;rbs_spacer=5-10bp;gc_cont=0.447;conf=100.00;score=128.39;cscore=113.30;sscore=15.09;rscore=12.82;uscore=-1.81;tscore=2.83;
Scaffold_199:27422-48104	Prodigal_v2.6.3	CDS	2034	3185	116.4	-	0	ID=1_4;partial=00;start_type=ATG;rbs_motif=GGAGG;rbs_spacer=5-10bp;gc_cont=0.439;conf=100.00;score=116.44;cscore=99.35;sscore=17.08;rscore=12.82;uscore=1.44;tscore=2.83;

(phamer) [valensan@puhti-login12 2_assembly]$ tail result.txt 
# Model Data: version=Prodigal.v2.6.3;run_type=Metagenomic;model="8|Bacteroides_fragilis_NCTC_9343|B|43.2|11|0";gc_cont=43.20;transl_table=11;uses_sd=0

Scaffold_50190	Prodigal_v2.6.3	CDS	79	1542	161.1	-	0	ID=28003_1;partial=01;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.458;conf=100.00;score=161.14;cscore=157.92;sscore=3.22;rscore=0.00;uscore=0.00;tscore=3.22;
# Sequence Data: seqnum=8;seqlen=1046;seqhdr="Scaffold_50191"

# Model Data: version=Prodigal.v2.6.3;run_type=Metagenomic;model="47|Xenorhabdus_nematophila_ATCC_19061|B|44.1|11|1";gc_cont=44.20;transl_table=11;uses_sd=1

Scaffold_50191	Prodigal_v2.6.3	CDS	1	420	20.7	+	0	ID=28004_1;partial=10;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.450;conf=99.14;score=20.66;cscore=17.44;sscore=3.22;rscore=0.00;uscore=0.00;tscore=3.22;
Scaffold_50191	Prodigal_v2.6.3	CDS	960	1046	24.5	+	0	ID=28004_2;partial=01;start_type=ATG;rbs_motif=GGAGG;rbs_spacer=5-10bp;gc_cont=0.414;conf=99.58;score=23.81;cscore=6.65;sscore=17.16;rscore=12.44;uscore=1.38;tscore=3.99;

```
 But, I found an error modifying subprocess output destination in the main script:
```
cat HeP-24_tmpphamer/pprodigal.log 
Traceback (most recent call last):
  File "/scratch/project_2007362/software/mambaforge/envs/phamer/bin/pprodigal", line 10, in <module>
    sys.exit(main())
  File "/scratch/project_2007362/software/mambaforge/envs/phamer/lib/python3.8/site-packages/pprodigal/pprodigal.py", line 293, in main
    protIdStart = append_fasta_file(workDir.name + "/chunk" + str(cur) + ".faa", protIdStart, proteinFile)
  File "/scratch/project_2007362/software/mambaforge/envs/phamer/lib/python3.8/site-packages/pprodigal/pprodigal.py", line 64, in append_fasta_file
    line = match.group(1) + str(startNum) + "_" + match.group(3) + match.group(4) + "\n"
AttributeError: 'NoneType' object has no attribute 'group'
```
I don't know what error could be.
Regards

**Comment by KennthShang** [comment]
I am not sure either. This should be an error caused by your data (name of the record in your fasta) or the prodigal.

You can try to run prodigal rather than pprodigal to see whether it helps.

Best,
Jiayu

**Comment by Sanrrone** [comment]
using prodigal instead pprodigal
```
(phamer) [valensan@puhti-login12 CD]$ cat HeP-24_tmpphamer/pprodigal.log 
-------------------------------------
PRODIGAL v2.6.3 [February, 2016]         
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.     
-------------------------------------

Error: cannot specify metagenomic sequence with a training file.
```

**Comment by KennthShang** [comment]
I am not sure. Maybe that means your input file is not in a standard FASTA format for prodigal. 

You should ask the author of prodigal for help: https://github.com/hyattpd/Prodigal

Best,
Jiayu

**Comment by Sanrrone** [comment]
Indeed, I solved it by editing the pprodigal.py file at line 62
modifying:
```
if match and match.group(3) == "1":
```
by
```
if match:
    if match.group(3) == "1":
```

However, that was just the first error:
```
Traceback (most recent call last):
  File "/scratch/project_2007362/software/PhaMer/PhaMer.py", line 41, in <module>
    pcs2idx = pkl.load(open(f'{transformer_fn}/pc2wordsid.dict', 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'HeP-24_tmpphamer/pc2wordsid.dict'
Using parallelized prodigal...
Running prodigal...
```
So, my last question in order to close the issue, is this still related with prodigal?

**Comment by KennthShang** [comment]
Did you rerun the code? Or you rerun the code and got the same error?

**Comment by Sanrrone** [comment]
I rerun the code and I got the same error. But, I also rerun the code with a small subsample of my original fasta and it works fine, so the problem must be some weird character on the headers. I'll check what's the header is giving me headaches

**Comment by KennthShang** [comment]
I mean the 'pc2wordsid'. 

If your preprocessing.py has been run correctly. It will not have the second error. Otherwise, phamer.py will not find the 'pc2wordsid' in the midfolder.

**Comment by Sanrrone** [comment]
Finally I solved it. I run only preprocessing.py in order to look for `pc2wordsid`. The problem was with `pprodigal`. For some reason the software is wrongly appending the sequences (I don't know why, the headers are ok). This causes that Diamond fails (which also I have to modify in order to track the exception produced) and at the middle of the test_protein.fa (produced by pprodigal) the file were miss formated like:
```
>scaffold_1113
CGTAGTCAGTCGTAGTCTGCGTAGTCTGAGTCTGATGCC
CTATGCGATGTCAGTCTGAGTCGTAGTCGTAGTCAGTCT
CGATTGCAGTCGTAGTCAGTGTCATGCTGATGCGTATGC>scaffold_1114
GTCAGTCAGTCGTAGTCGATCGTAGTCCCCCCCCCCCCT
GTCAGTCGTAGTCAGTGTCATGCGTAGTCAGTCAGTCAC
CGATGTCAGTCGTAGTCGTAGTCAGTCGTATGCTGAGTC
GCAGTCTGAGTCAGTCGTAGTCGTAGTCAGTCGTAGTCC
```
To solve it, I modified the `append_fasta_file` function from `pprodigal.py` and I add a `trgt.write("\n")` in order to add an extra end of line in each sequence. So the entire function looks like:
```
def append_fasta_file(file, startNum, targetFile):
    pattern = re.compile(r"(.*ID=)(\d+)_(\d+)(.*)")
    with open(targetFile, "a") as trgt:
        with open(file, "r") as input:
            for line in input:
                if line[0] == '>':
                    match = re.match(pattern, line)
                    if match:
                        if match.group(3) == "1":
                            startNum = startNum + 1

                        line = match.group(1) + str(startNum) + "_" + match.group(3) + match.group(4) + "\n"
                trgt.write(line)
        trgt.write("\n")
    return startNum
```

thanks for your help!
